export const COUNTRIES_FETCH_ALL = "COUNTRIES_FETCH_ALL"

export const SUBSCRIPTION_LISTS_DELETE_ONE = "SUBSCRIPTION_LISTS_DELETE_ONE"
export const SUBSCRIPTION_LISTS_ERROR = "SUBSCRIPTION_LISTS_ERROR"
export const SUBSCRIPTION_LISTS_FETCH_ONE = "SUBSCRIPTION_LISTS_FETCH_ONE"
export const SUBSCRIPTION_LISTS_FETCH_ALL = "SUBSCRIPTION_LISTS_FETCH_ALL"
export const SUBSCRIPTION_LISTS_RESET = "SUBSCRIPTION_LISTS_RESET"
